services:
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: ASP.NET_MyCMS
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=mycms;Username=postgres;Password=postgres
    volumes:
      - .:/src  # для горячей перезагрузки
      - dataprotection:/root/.aspnet/DataProtection-Keys

  postgres:
    image: postgres:16
    container_name: PostgeSQL_MyCMS
    restart: always
    environment:
      POSTGRES_DB: mycms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  dataprotection: